<footer>    
  <ul>
    <li><img id="logo" src="images/footertote.png"/></li>
    <li><a href="mentions.php">Mentions légales</a></li>
    <li><a href="faq.php">FAQ</a></li>
    <li><a href="contact.php">Contact</a></li>
    <li><a href="">Nous suivre</a>
      <div>
        <a id="facebook" href="https://www.facebook.com/toteworld.off/"><img src="images/icons/facebook.png"/></a>
        <a id="insta" href="https://www.instagram.com/toteworld.off/"><img src="images/icons/insta.png"/></a>
        <a id="twitter" href="https://twitter.com/tote_world"><img src="images/icons/twitter.png"/></a>
      </div>
    </li>  
  </ul>
</footer>