<header>
    <nav>
        <ul>
            <li><a href="index.php"><img id="logo" src="images/logo.png"/></a></li>
            <li><a href="nostotes.php">Nos Totes</a></li>
            <li><a href="proposition.php">À vous de jouer !</a></li>
            <li><a href="presentation.php">Qui sommes-nous ?</a></li>
            <li>
              <a id="panier" href="panier.php"><img src="images/icons/panier.png"/></a>
              <a id="pers" href="compte.php"><img src="images/icons/user.png"/></a>
              <a id="coeur" href="favoris.php"><img src="images/icons/coeur.png"/></a>
            </li>
        </ul>
    </nav>
</header>